name: 'build-and-push-devcontainer' 
on: # rebuild when devcontainer is updated
  push:
    paths:
      - '.devcontainer/**'
    branches:
      - main
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: 3
      
      - name: Get Version For Tag
        id: get_version
        run: |
          pip install -e .
          version=$(ghidrecomp -v)
          echo "ghidrecomp_ver=$version" >> $GITHUB_OUTPUT
          echo $ghidrecomp_ver

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/clearbluejar/ghidrecomp
          cacheFrom: ghcr.io/clearbluejar/ghidrecomp
          imageTag: latest,${{ steps.get_version.outputs.ghidrecomp_ver}}
          platform: linux/arm/v7,linux/arm64/v8,linux/amd64
        
          push: always
          runCmd: |
            find .
            find /ghidra