# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pytest Python Package In Devcontainer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Test with pytest on devcontainer    
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/clearbluejar/ghidra-python
        cacheFrom: ghcr.io/clearbluejar/ghidra-python
        push: never
        runCmd: |
          pip install --upgrade pip          
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .
          pytest -rA