# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pytest Python Package In Devcontainer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        runner: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v3
    # - name: Set up QEMU for multi-architecture builds
    #   uses: docker/setup-qemu-action@v2

    # - name: Setup Docker buildx for multi-architecture builds
    #   uses: docker/setup-buildx-action@v2
    #   with:
    #     use: true
    - name: Test with pytest on devcontainer    
      uses: devcontainers/ci@v0.3
      with:
        cacheFrom: ghcr.io/clearbluejar/ghidra-python

        push: never
        # platform: linux/amd64,linux/arm64
        runCmd: |
          pip install --upgrade pip          
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .
          pytest -rA
